version: "2"

run:
  timeout: 3m
  relative-path-mode: gomod

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - revive
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - std-error-handling
