apiVersion: v1
kind: ConfigMap
metadata:
  name: nostr-auth-policy
  namespace: nostr-auth
  labels:
    app.kubernetes.io/name: nostr-auth
    app.kubernetes.io/part-of: nostr-auth
data:
  config.json: |
    {
      "auth": {
        "enabled": true,
        "groups": {
          "admins": [
            "replace-me@example.com",
            "npub18us53gzgcc3p8mfmj7nf9kl5ugdkt0d0f9x97uxhc5pn96u2wnass2f0aj",
            "npub1q0xavqd3qm5yutgc3zrux9f35ezjyzmjvew9m3t4vmtq4llht0pqumvmun"
          ]
        },
        "apps": {
          "default": {
            "config": {
              "domains": [
                "nostr-auth.brunobernard.dev",
                "demo-nostr-auth.brunobernard.dev"
              ]
            },
            "users": [
              "group:admins"
            ]
          }
        }
      },
      "branding": {
        "background": {
          "source": {
            "type": "preset",
            "variant": "canyon-falls"
          }
        }
      }
    }
