apiVersion: v1
kind: ServiceAccount
metadata:
  name: nostr-auth
  namespace: nostr-auth
  labels:
    app.kubernetes.io/name: nostr-auth
    app.kubernetes.io/part-of: nostr-auth
automountServiceAccountToken: false
imagePullSecrets:
  - name: registry-secret
